In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [6]:
from sklearn.datasets import load_iris
iris= load_iris()
df= pd.DataFrame(iris.data, columns= iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
df['species']= pd.Categorical.from_codes(iris.target, iris.target_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [8]:
df.shape

(150, 5)

In [12]:
X= df.iloc[:,:3].values
y= df.iloc[:,4].values

In [13]:
y

[setosa, setosa, setosa, setosa, setosa, ..., virginica, virginica, virginica, virginica, virginica]
Length: 150
Categories (3, object): [setosa, versicolor, virginica]

In [14]:
encoder= LabelEncoder()
Y= encoder.fit_transform(y)
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
X,Y= shuffle(X,Y, random_state=0)

In [16]:
x_train,x_test,y_train, y_test= train_test_split(X,Y, test_size=0.25, random_state=0)

In [17]:
x_train

array([[4.8, 3.1, 1.6],
       [6.2, 3.4, 5.4],
       [6.4, 2.9, 4.3],
       [5.5, 4.2, 1.4],
       [5.9, 3.2, 4.8],
       [5. , 3.5, 1.6],
       [6.1, 2.6, 5.6],
       [6. , 3.4, 4.5],
       [7.9, 3.8, 6.4],
       [5.1, 3.7, 1.5],
       [6. , 3. , 4.8],
       [5.7, 2.8, 4.5],
       [4.3, 3. , 1.1],
       [5.5, 2.4, 3.7],
       [4.9, 2.5, 4.5],
       [7.2, 3.6, 6.1],
       [4.7, 3.2, 1.6],
       [6.7, 3. , 5. ],
       [4.9, 3.1, 1.5],
       [6.3, 2.9, 5.6],
       [5.6, 2.5, 3.9],
       [5.8, 2.7, 4.1],
       [6.5, 3. , 5.8],
       [6.4, 3.1, 5.5],
       [5.4, 3.9, 1.7],
       [5.7, 2.5, 5. ],
       [5.6, 2.9, 3.6],
       [6.5, 3.2, 5.1],
       [4.5, 2.3, 1.3],
       [5. , 3.3, 1.4],
       [6. , 2.2, 5. ],
       [6.5, 2.8, 4.6],
       [5.1, 3.3, 1.7],
       [6.9, 3.1, 5.4],
       [5.6, 2.8, 4.9],
       [4.9, 3.6, 1.4],
       [6.3, 3.3, 4.7],
       [7.3, 2.9, 6.3],
       [4.6, 3.2, 1.4],
       [7.2, 3. , 5.8],
       [5. , 3.5, 1.3],
       [5.3, 3.7

In [18]:
y_train

array([0, 2, 1, 0, 1, 0, 2, 1, 2, 0, 2, 1, 0, 1, 2, 2, 0, 1, 0, 2, 1, 1,
       2, 2, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 2, 0, 1, 2, 0, 2, 0, 0, 1, 0,
       1, 1, 0, 2, 1, 2, 1, 0, 2, 0, 2, 1, 0, 1, 2, 0, 1, 1, 1, 2, 1, 0,
       0, 2, 2, 1, 2, 0, 1, 0, 1, 1, 0, 2, 2, 1, 0, 0, 1, 0, 0, 0, 2, 2,
       2, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 2, 0, 0, 1, 1, 2, 2,
       1, 2])

In [19]:
clf= RandomForestClassifier(n_jobs=2, random_state=0)

In [21]:
clf.fit(x_train,y_train)
y_pred= clf.predict(x_test)
y_pred

array([2, 2, 2, 0, 1, 0, 2, 2, 2, 1, 0, 2, 0, 2, 1, 2, 0, 2, 1, 1, 2, 1,
       2, 1, 2, 0, 0, 0, 0, 0, 2, 2, 1, 1, 2, 2, 0, 2])

In [22]:
y_value= clf.predict(x_test[0:5])
y_value

array([2, 2, 2, 0, 1])

In [23]:
pred_name= iris.target_names[clf.predict(x_test[0:5])]
pred_name

array(['virginica', 'virginica', 'virginica', 'setosa', 'versicolor'],
      dtype='<U10')

In [28]:
true_names= iris.target_names[y_test[0:5]]
true_names

array(['virginica', 'virginica', 'virginica', 'setosa', 'versicolor'],
      dtype='<U10')

In [29]:
y_pred_probab= clf.predict_proba(x_test[0:5])
y_pred_probab

array([[0.  , 0.01, 0.99],
       [0.  , 0.12, 0.88],
       [0.  , 0.28, 0.72],
       [0.99, 0.01, 0.  ],
       [0.01, 0.96, 0.03]])

In [32]:
# DEVELOP A CONSUFION MATRIX USING CROSS TABULATION
data= pd.crosstab(iris.target_names[y_test], iris.target_names[y_pred], rownames=['Actual_names'], colnames=['Predicted_names'])
data

Predicted_names  setosa  versicolor  virginica
Actual_names                                  
setosa               11           0          0
versicolor            0           9          2
virginica             0           0         16

In [34]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[11,  0,  0],
       [ 0,  9,  2],
       [ 0,  0, 16]], dtype=int64)

In [36]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

94.73684210526315